import type { Metadata } from "next";
import { Geist, Geist_Mono, Bebas_Neue } from "next/font/google";
import localFont from "next/font/local";
import TransitionFunc from "../transition/transition";
import StaticSwipeBootSequence from "@/components/BootSequence";
import "./globals.css";
import Topbar from "@/components/Topbar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const bebasNeue = Bebas_Neue({
  variable: "--font-bebas-neue",
  weight: "400",
  subsets: ["latin"],
});

const AkiraExpanded = localFont({
  src: "../public/fonts/AkiraExpanded.woff2",
  variable: "--font-akira",
});

export const metadata: Metadata = {
  title: "F1 2020",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} ${AkiraExpanded.variable} ${bebasNeue.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col overflow-y-scroll no-scrollbar">
        <StaticSwipeBootSequence />
        <Topbar/>
        <TransitionFunc>{children}</TransitionFunc>
      </body>
    </html>
  );
}
