import type { Metadata } from "next";
import Image from "next/image";
import { Geist, Geist_Mono } from "next/font/google";
import localFont from "next/font/local";
import Navbar from "../components/navbar";
import TransitionFunc from "../transition/transition";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const AkiraExpanded = localFont({
  src: "../public/fonts/AkiraExpanded.woff2",
  variable: "--font-akira",
});

export const metadata: Metadata = {
  title: "F1 2020",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} ${AkiraExpanded.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col overflow-y-scroll no-scrollbar">
        {/* header and logos */}
        <div className="w-full bg-white absolute z-4 top-0 flex justify-center items-center p-3">
          <Image
            src="../../../logos/F1.svg"
            alt=""
            width={100}
            height={100}
          />
        </div>
        <TransitionFunc>{children}</TransitionFunc>
      </body>
    </html>
  );
}
